# fly.toml app configuration file generated for 5m555 on 2026-05-02T00:03:32Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '5m555'
primary_region = 'bom'

[build]
  dockerfile = 'Dockerfile'

[env]
  ARMED_FOR_LIVE = 'false'
  COINS = 'btc,eth,xrp,doge,hype,bnb,sol'
  DB_PATH = '/data/bot.sqlite3'
  DRY_RUN = 'true'
  ENTRY_MAX_PRICE = '0.97'
  ENTRY_THRESHOLD = '0.58'
  HEALTHCHECK_PORT = '8080'
  KILL_SWITCH = 'false'
  LOG_LEVEL = 'INFO'
  MAX_CONCURRENT_POSITIONS = '20'
  MAX_DAILY_LOSS_USD = '50.0'
  MIN_SECONDS_REMAINING = '20'
  POLY_AUTO_DERIVE_CREDS = 'true'
  POLY_SIGNATURE_TYPE = '2'
  POSITION_SIZE_USD = '1.0'
  TRADING_ENABLED = 'false'

[[mounts]]
  source = 'poly5m_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/healthz'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
